version: '2'
services:

  certbot:
    image: foodcoops/certbot:latest
    restart: always
    environment:
      CERTBOT_DOMAINS: |-
        ${HOSTNAME},vers.${DOMAIN}
      CERTBOT_EMAIL: systems-all@${DOMAIN}
      CERTBOT_TOUCH_FILE: /triggers/reload-certs
    volumes:
      - certs:/certs
      - triggers:/triggers

  foodsoft:
    build: foodsoft
    restart: always
    environment:
      - DATABASE_URL=mysql2://foodsoft:${FOODSOFT_DB_PASSWORD}@mariadb/foodsoft_vkmkm?encoding=utf8mb4
      - EMAIL_SENDER=noreply@${DOMAIN}
      #- ERROR_RECIPIENTS=
      - HOSTNAME
      - QUEUE=foodsoft_notifier
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY_BASE=${FOODSOFT_SECRET_KEY_BASE}
      - SHAREDLISTS_DATABASE_URL=mysql2://foodsoft:${FOODSOFT_DB_PASSWORD}@mariadb/sharedlists?encoding=utf8mb4
      - MAILER_PREFIX=foodsoft+
      - SMTP_DOMAIN=${HOSTNAME}
      - SMTP_ADDRESS
      - SMTP_PORT
      - SMTP_USER_NAME
      - SMTP_PASSWORD

  foodsoft_cron:
    extends: foodsoft
    command: ./proc-start cron

  foodsoft_worker:
    extends: foodsoft
    command: ./proc-start worker

  foodsoft_smtp:
    extends: foodsoft
    command: ./proc-start mail
    environment:
      - SMTP_SERVER_PORT=2525
      - SMTP_SERVER_HOST=0.0.0.0

  haproxy:
    build: haproxy
    restart: always
    environment:
      - HAPROXY_RELOAD_FILE=/triggers/reload-certs
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/certs:ro
      - triggers:/triggers

  mariadb:
    image: mariadb:10.3
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_ABSOLUTE_URI=https://${HOSTNAME}/phpmyadmin/
      - PMA_HOST=mariadb

  redis:
    image: redis:3.2-alpine
    restart: always

  sharedlists:
    image: foodcoops/sharedlists:latest
    restart: always
    environment:
      - DATABASE_URL=mysql2://sharedlists:${SHAREDLISTS_DB_PASSWORD}@mariadb/sharedlists?encoding=utf8mb4
      - SECRET_TOKEN=${SHAREDLISTS_SECRET_KEY_BASE}
      - RAILS_RELATIVE_URL_ROOT=/sharedlists
      - MAILER_DOMAIN=${HOSTNAME}
      - MAILER_PREFIX=sharedlists+
    volumes:
      - supplier_assets:/usr/src/app/supplier_assets

  sharedlists_cron:
    extends: sharedlists
    command: ./proc-start cron

  sharedlists_smtp:
    extends: sharedlists
    command: ./proc-start mail
    environment:
      - SMTP_SERVER_PORT=2525
      - SMTP_SERVER_HOST=0.0.0.0

  smtp:
    build: smtp
    restart: always
    environment:
      - HOSTNAME
      - DOMAIN=${HOSTNAME}
      - POSTFIX_RELOAD_FILE=/triggers/reload-certs
    ports:
      - "25:25"
    volumes:
      - certs:/certs:ro
      - triggers:/triggers

volumes:
  certs:
  mariadb:
  supplier_assets:
  triggers:
